### ISSUE TITLE
请问怎么导出axios给Cocos Creator 3.0做插件用？

### ISSUE THREAD

**Issue by 2505817596** [AILHC/EasyGameFrameworkOpen#12]
运行yarn run build:system命令时，出现

![image](https://user-images.githubusercontent.com/37748815/104158118-a4c89a80-5427-11eb-9f75-5d3364047cf5.png)

**Comment by AILHC** [comment]
![78}N EDSTY_DGAYE5(D%DGY](https://user-images.githubusercontent.com/21373809/104160307-dfcccd00-542b-11eb-845b-1fe9c7bbda53.jpg)
![3L9_UVI@_@C$HTP6KP@55Q1](https://user-images.githubusercontent.com/21373809/104160312-e0fdfa00-542b-11eb-8c47-ebc57b196d94.jpg)
![}@@L_9RLK8D74L}UK( 1UDQ](https://user-images.githubusercontent.com/21373809/104160315-e3f8ea80-542b-11eb-97c2-cb91f60db99b.jpg)
![BNCG% LL~V O_QYBF1}DLPL](https://user-images.githubusercontent.com/21373809/104160317-e52a1780-542b-11eb-907e-abe84768d994.jpg)

补充一下你的代码

**Comment by AILHC** [comment]
@2505817596 这个是我的构建工具缺乏对import json文件的支持，我改一下

**Comment by AILHC** [comment]
@2505817596 
你需要的库，我已经打出来了。
可以npm i c3daxios 安装，然后再安装axios库（用作类型声明）

**Comment by 2505817596** [comment]
> @2505817596
> 你需要的库，我已经打出来了。
> 可以npm i c3daxios 安装，然后再安装axios库（用作类型声明）

多谢大神的回复，必须star

**Comment by AILHC** [comment]
@2505817596 谢谢支持
这个构建还是会有问题的
原因
axios内置了nodejs端的http支持
就是getDefaultAdapter
构建之后还要删除index.js中一些东西
```js
//改掉
['../../../node_modules/axios/lib/adapters/http', '../../../node_modules/axios/lib/adapters/http.js'] -> []
//删掉
setters: [function () {}, function (module) {
      http = module.default;
    }]
    
    
```
